Team submission + breaking down address in User schema
fdolisy/TeamUp pull request #37
Opened 2023-03-06 08:41 UTC by Swarita

2023-03-06 08:42 UTC, Swarita commented
Changed server\routes\api\teams.js and added a PUT request for team submission. To verify, make a PUT request in Postman and add the timings of a specific team. (Have an already created team's ID ready to add to the path: http://localhost:8082/api/teams/submit_team/:id).

2023-03-06 19:36 UTC, cadybaltz requested changes
Tested and works for me, see the comments for some small changes

2023-03-06 19:36 UTC, cadybaltz commented on server/routes/api/teams.js
> +    res.send("Congratulaions! You submitted your team! Is team submitted:" + updatedTeam.is_finalized);
Minor thing: there's a misspelling here

2023-03-06 19:36 UTC, cadybaltz commented on server/config.js
> +ATLAS_URI=mongodb+srv://Cluster13473:teamup@cluster13473.ziewtw1.mongodb.net/test?retryWrites=true&w=majority
This file should not be committed to our repo - renaming to config.env should make sure it is included in our .gitignore!

2023-03-06 22:04 UTC, cadybaltz approved these changes

2023-03-07 04:43 UTC, fdolisy commented on server/routes/api/registration.js
> +        city: req.body.address,
Shouldn't this be "city: req.body.city"?

2023-03-07 05:17 UTC, fdolisy approved these changes

2023-03-07 05:18 UTC, merged